import React from 'react';
import NextLink from 'next/link';
import { useRouter } from 'next/router'
import {
  Container,
  Box,
  Text,
  Link,
  Flex,
  Pipe,
  Popover,
  ChromelessButton,
  Badge,
  Heading,
  Divider,
  VisuallyHidden,
  IconButton,
} from '@modulz/radix';
import { Logo } from './Logo';
import { HideInProd } from './HideInProd';
import { PlusIcon, HamburgerIcon, CrossIcon } from '@modulz/radix-icons';

export const Header = () => {
  const { route } = useRouter();
  const [isOpen, setIsOpen] = React.useState(false);
  const [isNavOpen, setIsNavOpen] = React.useState(false);
  const buttonRef = React.useRef<HTMLButtonElement>(null);

  function closeNav() {
    setIsNavOpen(false);
  }

  function toggleNav() {
    setIsNavOpen(!isNavOpen);
  }

  React.useEffect(() => {
    if (isNavOpen) {
      document.body.style.overflowY = 'scroll';
      document.body.style.position = 'fixed';
    } else {
      document.body.style.overflowY = '';
      document.body.style.position = '';
    }
  }, [isNavOpen]);

  return (
    <Container size={2} sx={{ maxWidth: 'none' }}>
      <Flex py={4} sx={{ alignItems: 'flex-start' }}>
        <NextLink href="/" passHref>
          <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>
            <VisuallyHidden>Modulz homepage</VisuallyHidden>
            <Logo aria-hidden />
          </Link>
        </NextLink>

        <Flex ml="auto" sx={{ flexDirection: ['row', 'row'], alignItems: ['center', 'center'] }}>
          <ChromelessButton
            ref={buttonRef}
            onClick={() => setIsOpen(true)}
            sx={{
              display: ['none', 'block'],
              py: 1,
              px: 2,
              borderRadius: 1,
              bg: isOpen ? 'gray200' : undefined,
              ':hover': { bg: 'gray200' },
            }}
          >
            <Text size={3} sx={{ color: 'gray700' }}>
              <Flex as="span" sx={{ alignItems: 'center' }}>
                Product
                <Box as="span" ml={1}>
                  <PlusIcon />
                </Box>
              </Flex>
            </Text>
          </ChromelessButton>

          <Popover targetRef={buttonRef} isOpen={isOpen} onClose={() => setIsOpen(false)}>
            <Box py={1} sx={{ width: 300 }}>
              <Box py={2} px={4}>
                <Heading size={0} sx={{ color: 'gray600' }}>
                  Theme <Badge ml={1}>Coming soon</Badge>
                </Heading>
                <Text size={2} sx={{ color: 'gray600', lineHeight: 1 }}>
                  Advanced tooling for defining scale-based design tokens.
                </Text>
              </Box>
              <Box py={2} px={4}>
                <Heading size={0} sx={{ color: 'gray600' }}>
                  Editor <Badge ml={1}>Coming soon</Badge>
                </Heading>
                <Text size={2} sx={{ color: 'gray600', lineHeight: 1 }}>
                  A visual code editor for building a component library without writing code.
                </Text>
              </Box>

              <NextLink href="/styleguide" passHref>
                <Box
                  as="a"
                  py={2}
                  px={4}
                  sx={{ textDecoration: 'none', color: 'inherit', display: 'block', ':hover': { bg: 'gray200' } }}
                  onClick={() => {
                    setIsOpen(false);
                    closeNav();
                  }}
                >
                  <Heading size={0}>
                    Style guide
                    <Badge variant="blue" ml={1}>
                      New
                    </Badge>
                  </Heading>
                  <Text size={2} sx={{ color: 'gray700', lineHeight: 1 }}>
                    Handoff your design system with a gorgeous, generated style guide.
                  </Text>
                </Box>
              </NextLink>

              <Divider my={1} />

              <a href="https://radix.modulz.app" style={{ textDecoration: 'none', color: 'inherit' }}>
                <Box as="span" py={2} px={4} sx={{ display: 'block', ':hover': { bg: 'gray200' } }}>
                  <Heading size={0}>Radix</Heading>
                  <Text size={2} sx={{ color: 'gray700', lineHeight: 1 }}>
                    Our very own design system—generated by Modulz.
                  </Text>
                </Box>
              </a>
            </Box>
          </Popover>

          <Text size={3} sx={{ color: 'gray700', display: ['none', 'block'] }} ml={[2, 6]}>
            <NextLink href="/about" passHref>
              <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>About</Link>
            </NextLink>
          </Text>
          <HideInProd>
            <Text size={3} sx={{ color: 'gray700', display: ['none', 'block'] }} ml={[4, 7]}>
              <NextLink href="/learn" passHref>
                <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>Learn</Link>
              </NextLink>
            </Text>
          </HideInProd>
          <Text size={3} sx={{ color: 'gray700', display: ['none', 'block'] }} ml={[4, 7]}>
            <NextLink href="/blog" passHref>
              <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>Blog</Link>
            </NextLink>
          </Text>
          <HideInProd>
            <Text size={3} sx={{ color: 'gray700', display: ['none', 'block'] }} ml={[4, 7]}>
              <NextLink href="/pricing" passHref>
                <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>Pricing</Link>
              </NextLink>
            </Text>
          </HideInProd>

          <Pipe mx={[2, 5]} sx={{ display: ['none', 'block'] }} />

          <Text size={3} sx={{ color: 'gray700', display: ['none', 'block'] }}>
            <Link href="https://core.modulz.app" sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }}>
              Login
            </Link>
          </Text>

          <Box sx={{ display: ['block', 'none'] }}>
            <IconButton aria-label={isNavOpen ? 'Close menu' : 'Open menu'} onClick={toggleNav} isActive={isNavOpen}>
              {isNavOpen ? <CrossIcon /> : <HamburgerIcon />}
            </IconButton>
          </Box>
        </Flex>
      </Flex>

      {isNavOpen && (
        <Box sx={{ background: 'white', height: '100vh', display: ['block', 'none']}}>
          <Text size={3} sx={{ color: route === '/about' ? 'blue700' : 'gray700', display: 'block', py: 1, px: 2 }}>
            <NextLink href="/about" passHref>
              <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }} onClick={closeNav}>About</Link>
            </NextLink>
          </Text>
          <ChromelessButton
            ref={buttonRef}
            onClick={() => setIsOpen(true)}
            sx={{
              py: 1,
              px: 2,
              mt: 2,
              borderRadius: 1,
              bg: isOpen ? 'gray200' : undefined,
              ':hover': { bg: 'gray200' },
            }}
          >
            <Text size={3} sx={{ color: route === '/styleguide' ? 'blue700' : 'gray700', display: ['block', 'none'] }}>
              <Flex as="span" sx={{ alignItems: 'center' }}>
                Product
                <Box as="span" ml={1}>
                  <PlusIcon />
                </Box>
              </Flex>
            </Text>
          </ChromelessButton>
          <HideInProd>
            <Text size={3} sx={{ color: route === '/learn' ? 'blue700' : 'gray700', display: 'block', mt: 2, py: 1, px: 2 }}>
              <NextLink href="/learn" passHref>
                <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }} onClick={closeNav}>Learn</Link>
              </NextLink>
            </Text>
          </HideInProd>
          <HideInProd>
            <Text size={3} sx={{ color: route === '/blog' ? 'blue700' : 'gray700', display: 'block', mt: 2, py: 1, px: 2 }}>
              <NextLink href="/blog" passHref>
                <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }} onClick={closeNav}>Blog</Link>
              </NextLink>
            </Text>
          </HideInProd>
          <HideInProd>
            <Text size={3} sx={{ color: route === '/pricing' ? 'blue700' : 'gray700', display: 'block', mt: 2, py: 1, px: 2 }}>
              <NextLink href="/pricing" passHref>
                <Link sx={{ color: 'inherit', ':focus': { boxShadow: 'none' } }} onClick={closeNav}>Pricing</Link>
              </NextLink>
            </Text>
          </HideInProd>
        </Box>
      )}
    </Container>
  );
};
